<?php

/**
 * BaseEmployee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $e_id
 * @property string $fname
 * @property string $lname
 * @property string $address
 * @property Doctrine_Collection $User
 * 
 * @method string              getEId()     Returns the current record's "e_id" value
 * @method string              getFname()   Returns the current record's "fname" value
 * @method string              getLname()   Returns the current record's "lname" value
 * @method string              getAddress() Returns the current record's "address" value
 * @method Doctrine_Collection getUser()    Returns the current record's "User" collection
 * @method Employee            setEId()     Sets the current record's "e_id" value
 * @method Employee            setFname()   Sets the current record's "fname" value
 * @method Employee            setLname()   Sets the current record's "lname" value
 * @method Employee            setAddress() Sets the current record's "address" value
 * @method Employee            setUser()    Sets the current record's "User" collection
 * 
 * @package    project
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseEmployee extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('employee');
        $this->hasColumn('e_id', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '10',
             ));
        $this->hasColumn('fname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('lname', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('address', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '1000',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User', array(
             'local' => 'e_id',
             'foreign' => 'employee_id'));
    }
}