<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2023/04/21 20:07:01

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=project',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
